name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

env:
  IMAGE_NAME: todo-app-node
  REGISTRY: docker.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current time for version tag
        id: date
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.date.outputs.TAG }}

  deploy-to-railway:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Railway
        run: |
          railway up \
            --service=1e483560-62ff-4cff-bc66-e0758daf0658 \
            --environment=6d2cdaa1-97a2-4150-a79c-0ecd8834a43a || true
